name = "invoice-generator-1"
compatibility_date = "2026-09-15"
pages_build_output_dir = "frontend"

[[d1_databases]]
binding = "DB"
database_name = "jcf-invoices"
database_id = "c908b5ba-dfee-4d71-a104-fed61f658376"
